dist: bionic

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

# Normally, travis tries `git submodule update --init --recursive`, but
# that fails for us right now due to some submodules from `macaw`. We
# only really care about one recursive submodule, so we do the update
# manually in the `script` section.
git:
  submodules: false


matrix:
  include:
    - env: CABALVER="3.0" GHCVER="8.6.5"
      compiler: ": #GHC 8.6.5"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5,python3-venv], sources: [hvr-ghc]}}
      python: 3.7
#    - env: CABALVER="3.0" GHCVER="8.4.4"
#      compiler: ": #GHC 8.4.4"
#      addons: {apt: {packages: [cabal-install-3.0,ghc-8.4.4], sources: [hvr-ghc]}}

before_install:
  - unset CC
  - export PATH=/opt/ghc/bin:$HOME/.cabal/bin:$PATH

script:
  - git submodule init
  - git submodule update
  - (cd deps/abcBridge && git submodule init && git submodule update)
  - cabal v2-update
  - cabal v2-build -j --disable-optimization cryptol-remote-api
  - cabal v2-build -j --disable-optimization saw-remote-api
  - cabal v2-test cryptol-remote-api
  - cabal v2-test saw-remote-api
