dist: trusty
sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

# Normally, travis tries `git submodule update --init --recursive`, but
# that fails for us right now due to some submodules from `macaw`. We
# only really care about one recursive submodule, so we do the update
# manually in the `script` section.
git:
  submodules: false

addons: {apt: {packages: [python3-venv]}}

matrix:
  include:
    - env: CABALVER="3.0" GHCVER="8.6.5"
      compiler: ": #GHC 8.6.5"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5,python3-venv], sources: [hvr-ghc]}}
#    - env: CABALVER="3.0" GHCVER="8.4.4"
#      compiler: ": #GHC 8.4.4"
#      addons: {apt: {packages: [cabal-install-3.0,ghc-8.4.4], sources: [hvr-ghc]}}

before_install:
  - unset CC
  - export PATH=/opt/ghc/bin:$HOME/.cabal/bin:$PATH

script:
  - cabal v2-update
  - cabal v2-build -j --disable-optimization --constraint="cryptonite -support_aesni" file-echo-api
  - cabal v2-test --constraint="cryptonite -support_aesni" argo
  - cabal v2-test --constraint="cryptonite -support_aesni" file-echo-api
