resolver: lts-13.27

packages:
- argo
- cryptol-remote-api
- saw-remote-api

extra-deps:
# local things
- deps/cryptol/
- deps/saw-script
- deps/abcBridge/
- deps/aig/
- deps/crucible/crucible/
- deps/crucible/crucible-saw/
- deps/crucible/crucible-llvm/
- deps/crucible/crucible-jvm/
- deps/crucible/crux/
- deps/crucible/what4/
- deps/cryptol-verifier/
- deps/jvm-parser/
- deps/jvm-verifier/
- deps/llvm-pretty/
- deps/llvm-pretty-bc-parser/
- deps/llvm-verifier/
- deps/parameterized-utils/
- deps/saw-core-aig/
- deps/saw-core-sbv/
- deps/saw-core/
- deps/flexdis86/
- deps/flexdis86/binary-symbols
- deps/macaw/base/
- deps/macaw/symbolic/
- deps/macaw/x86/
- deps/macaw/x86_symbolic/
- deps/elf-edit/
- deps/dwarf/
- deps/saw-core-what4/
# not local things
- IfElse-0.85
- itanium-abi-0.1.1.1
- boomerang-1.4.5.6
- fgl-visualize-0.1.0.1
- GraphSCC-1.0.4
- base-compat-0.10.5
- monadLib-3.9
- network-3.0.1.0
- panic-0.4.0.1
- simple-smt-0.9.4
- sbv-8.3
- config-schema-1.0.0.0
- config-value-0.6.3.1
- simple-get-opt-0.3
- th-abstraction-0.3.1.0
- aeson-1.4.4.0

# stack's metadata gets out of date
allow-newer: true
