version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts

    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - cci-demo-haskell-v1-{{ checksum "argo/argo.cabal" }}-{{ checksum "argo/stack.yaml" }}-{{ checksum "saw-remote-api/saw-remote-api.cabal"}}-{{ checksum "cryptol-remote-api/cryptol-remote-api.cabal"}}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack test
      - run:
          name: Install executable
          command: stack install
      - save_cache:
          name: Cache Dependencies
          key: cci-demo-haskell-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - ".stack"
            - ".stack-work"
      - run:
          name: Print the Current Time
          command: date
